### ISSUE TITLE
How to install 'latentvelo'

### ISSUE THREAD

**Issue by parkjooyoung99** [Spencerfar/LatentVelo#1]
I am trying to use latentvelo with my data and want to know how to install the module. 
I have tried with pip install but is not working. 
Would there be any recommended way to install 'latentvelo'?

Thank you :)

![image](https://user-images.githubusercontent.com/77565848/188344403-95a5831f-36f9-44ab-a935-6fd991a0fcf2.png)

**Comment by Spencerfar** [comment]
Sorry, I haven't released the package yet, but it will be available to install with pip soon.

**Comment by kxxxjo** [comment]
Hi, @Spencerfar 

I want to use your latentvelo on my scRNAseq data, but pip install is still not working. 

so, would you let me know how to install latentvelo?

Thanks!

Best,
KJ

**Comment by Spencerfar** [comment]
Download and run "python setup.py install" in the main directory.
